# Generated by Django 6.0.5 on 2026-07-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcelPath', '0002_alter_contact_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50)),
                ('receiver_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=10)),
                ('parcel_weight', models.CharField(max_length=4)),
                ('pickup_address', models.CharField(max_length=50)),
                ('delivery_address', models.CharField(max_length=50)),
                ('parcel_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
