# Generated by Django 6.0.5 on 2026-08-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcelPath', '0003_book_parcel_alter_contact_date_alter_contact_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_parcel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
