# Generated by Django 6.0.5 on 2026-08-03 03:27

import ParcelPath.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcelPath', '0004_book_parcel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_parcel',
            name='status',
            field=models.CharField(default='Parcel Booked', max_length=50),
        ),
        migrations.AddField(
            model_name='book_parcel',
            name='tracking_id',
            field=models.CharField(default=ParcelPath.models.generate_tracking_id, max_length=20, unique=True),
        ),
    ]
