# Generated by Django 6.0.5 on 2026-08-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcelPath', '0005_book_parcel_status_book_parcel_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_parcel',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
