# Generated by Django 6.0.5 on 2026-08-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcelPath', '0006_book_parcel_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_parcel',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
