# Generated by Django 6.1 on 2026-09-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcelPath', '0007_alter_book_parcel_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_parcel',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online Payment'), ('COD', 'Cash on Delivery')], default='ONLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='book_parcel',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
