# Generated by Django 6.1 on 2026-09-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcelPath', '0008_book_parcel_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_parcel',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='book_parcel',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book_parcel',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
