# Generated by Django 6.1 on 2026-09-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParcelPath', '0009_remove_book_parcel_qr_code_book_parcel_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_parcel',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
