# Generated by Django 6.0.5 on 2026-08-19 03:48

import custom_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50)),
                ('receiver_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=10)),
                ('parcel_weight', models.CharField(max_length=4)),
                ('pickup_address', models.CharField(max_length=50)),
                ('delivery_address', models.CharField(max_length=50)),
                ('parcel_type', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tracking_id', models.CharField(default=custom_admin.models.generate_tracking_id, max_length=20, unique=True)),
                ('status', models.CharField(default='Parcel Booked', max_length=50)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
    ]
