# Generated by Django 6.1 on 2026-09-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Read', 'Read'), ('Replied', 'Replied')], default='New', max_length=20)),
            ],
        ),
    ]
