# Generated by Django 6.1 on 2026-09-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_alter_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
    ]
