# Generated by Django 6.1 on 2026-09-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_alter_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_parcel',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book_parcel',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book_parcel',
            name='payment_method',
            field=models.CharField(default='razorpay', max_length=20),
        ),
        migrations.AddField(
            model_name='book_parcel',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='book_parcel',
            name='parcel_type',
            field=models.CharField(max_length=50),
        ),
    ]
