# Generated by Django 6.1 on 2026-09-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0006_book_parcel_order_id_book_parcel_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_parcel',
            name='parcel_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='book_parcel',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cod', 'COD')], default='cod', max_length=20),
        ),
    ]
